/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup Handler */
        post: operations["signup_handler_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Handler */
        post: operations["login_handler_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Handler */
        post: operations["logout_handler_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_api_v1_analyses_get"];
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/leaves/expand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expand Leaf */
        post: operations["expand_leaf_api_v1_analyses__analysis_id__leaves_expand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /** Delete Analysis */
        delete: operations["delete_analysis_api_v1_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        /** Patch Analysis */
        patch: operations["patch_analysis_api_v1_analyses__analysis_id__patch"];
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/leaves/{line_no}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Pin Leaf */
        patch: operations["pin_leaf_api_v1_analyses__analysis_id__leaves__line_no__pin_patch"];
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Analyses */
        get: operations["search_analyses_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/encyclopedia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Encyclopedia */
        get: operations["get_encyclopedia_api_v1_encyclopedia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisCreateRequest */
        AnalysisCreateRequest: {
            /** Code */
            code: string;
            /** Language */
            language?: "python" | null;
        };
        /** AnalysisCreateResponse */
        AnalysisCreateResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Code Original */
            code_original: string;
            /** Code Processed */
            code_processed: string;
            /** Code Sha256 */
            code_sha256: string;
            /** Language */
            language: string;
            /** Line Count Original */
            line_count_original: number;
            /** Line Count Processed */
            line_count_processed: number;
            /** Line Mapping */
            line_mapping: {
                [key: string]: number;
            };
            /** Forest */
            forest: string;
            /** Tree */
            tree: string;
            /** Line Explanations */
            line_explanations: components["schemas"]["LineExplanationItem"][];
            /** Deep Leaves */
            deep_leaves: components["schemas"]["DeepLeafItem"][];
            /** Tags */
            tags: string[];
            /** Key Concepts */
            key_concepts: components["schemas"]["KeyConceptCreateItem"][];
            /** Created At */
            created_at: string;
            /** Daily Used */
            daily_used: number;
            /** Leaf Counter */
            leaf_counter: number;
            /** Is Favorite */
            is_favorite: boolean;
            /** Memo */
            memo: string | null;
            /** Cache Hit */
            cache_hit: boolean;
        };
        /** AnalysisDetailResponse */
        AnalysisDetailResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Created At */
            created_at: string;
            /** Language */
            language: string;
            /** Code Original */
            code_original: string;
            /** Code Processed */
            code_processed: string;
            /** Forest */
            forest: string;
            /** Tree */
            tree: string;
            /** Tags */
            tags: string[];
            /** Memo */
            memo: string | null;
            /** Is Favorite */
            is_favorite: boolean;
            /** Line Explanations */
            line_explanations: components["schemas"]["LineExplanationItem"][];
            /** Deep Leaves */
            deep_leaves: components["schemas"]["DeepLeafItem"][];
            /** Key Concepts */
            key_concepts: components["schemas"]["KeyConceptDetailItem"][];
        };
        /** AnalysisPatchRequest */
        AnalysisPatchRequest: {
            /** Tags */
            tags?: string[] | null;
            /** Memo */
            memo?: string | null;
            /** Is Favorite */
            is_favorite?: boolean | null;
        };
        /** DeepLeafItem */
        DeepLeafItem: {
            /** Line No */
            line_no: number;
            /** Deep */
            deep: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KeyConceptCreateItem */
        KeyConceptCreateItem: {
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            /** Is New */
            is_new: boolean;
        };
        /** KeyConceptDetailItem */
        KeyConceptDetailItem: {
            /** Name */
            name: string;
            /** Definition */
            definition: string;
        };
        /** LeafExpandRequest */
        LeafExpandRequest: {
            /** Line No */
            line_no: number;
        };
        /** LeafPinRequest */
        LeafPinRequest: {
            /** Deep Text */
            deep_text: string;
        };
        /** LineExplanationItem */
        LineExplanationItem: {
            /** Line No */
            line_no: number;
            /** Short */
            short: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Nickname */
            nickname: string;
            /** Level */
            level: number;
            /** Level Auto */
            level_auto: boolean;
            /** First Login Completed At */
            first_login_completed_at: string | null;
            /** Sound Enabled */
            sound_enabled: boolean;
            /** Daily Used */
            daily_used: number;
            /** Daily Limit */
            daily_limit: number;
            /** Daily Remaining */
            daily_remaining: number;
            /** Leaf Counter */
            leaf_counter: number;
            reward: components["schemas"]["RewardPublic"];
            title: components["schemas"]["TitleInfo"];
        };
        /** RewardPublic */
        RewardPublic: {
            /** Caterpillar Balance */
            caterpillar_balance: number;
            /** Caterpillar Total Earned */
            caterpillar_total_earned: number;
            /** Caterpillar Total Spent */
            caterpillar_total_spent: number;
            /** Shield Count */
            shield_count: number;
            /** Shield Used Total */
            shield_used_total: number;
            /** Streak Current */
            streak_current: number;
            /** Streak Max */
            streak_max: number;
            /** Streak Last Date */
            streak_last_date: string | null;
            /** Analysis Count Total */
            analysis_count_total: number;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Nickname */
            nickname: string;
            /** Agreed Terms */
            agreed_terms: boolean;
            /** Agreed Privacy */
            agreed_privacy: boolean;
        };
        /** TitleInfo */
        TitleInfo: {
            /** Stage */
            stage: number;
            /** Emoji */
            emoji: string;
            /** Label */
            label: string;
            /** Next Threshold */
            next_threshold: number | null;
        };
        /** UserUpdateRequest */
        UserUpdateRequest: {
            /** Level */
            level?: number | null;
            /** First Login Completed */
            first_login_completed?: boolean | null;
            /** Sound Enabled */
            sound_enabled?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_handler_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_handler_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_handler_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_api_v1_analyses_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expand_leaf_api_v1_analyses__analysis_id__leaves_expand_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeafExpandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_api_v1_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_analysis_api_v1_analyses__analysis_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pin_leaf_api_v1_analyses__analysis_id__leaves__line_no__pin_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
                line_no: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeafPinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_analyses_api_v1_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_encyclopedia_api_v1_encyclopedia_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
